Contexts for 7.11.0
This commit was created by the elastic-dockerfiles-publisher.

diff --git a/elasticsearch/Dockerfile b/elasticsearch/Dockerfile
--- a/elasticsearch/Dockerfile
+++ b/elasticsearch/Dockerfile
@@ -24,28 +24,46 @@ RUN set -eux ; \
         x86_64)  tini_bin='tini-amd64' ;; \
         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;; \
     esac ; \
-    curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ; \
-    curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ; \
+    curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ; \
+    curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ; \
     sha256sum -c ${tini_bin}.sha256sum ; \
     rm ${tini_bin}.sha256sum ; \
-    mv ${tini_bin} /tini ; \
-    chmod +x /tini
+    mv ${tini_bin} /bin/tini ; \
+    chmod +x /bin/tini
 
 RUN mkdir /usr/share/elasticsearch
 WORKDIR /usr/share/elasticsearch
 
-
-RUN curl --retry 8 -S -L \
+RUN curl --retry 10 -S -L \
       --output /opt/elasticsearch.tar.gz \
-      https://artifacts-no-kpi.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-linux-$(arch).tar.gz
+      https://artifacts-no-kpi.elastic.co/downloads/elasticsearch/elasticsearch-7.11.0-linux-$(arch).tar.gz
 
+RUN tar -zxf /opt/elasticsearch.tar.gz --strip-components=1
 
-RUN tar zxf /opt/elasticsearch.tar.gz --strip-components=1
-RUN sed -i -e 's/ES_DISTRIBUTION_TYPE=tar/ES_DISTRIBUTION_TYPE=docker/' /usr/share/elasticsearch/bin/elasticsearch-env
-RUN mkdir -p config config/jvm.options.d data logs
-RUN chmod 0775 config config/jvm.options.d data logs
-COPY config/elasticsearch.yml config/log4j2.properties config/
-RUN chmod 0660 config/elasticsearch.yml config/log4j2.properties
+# The distribution includes a `config` directory, no need to create it
+COPY config/elasticsearch.yml config/
+COPY bin/transform-log4j-config-7.11.0.jar /tmp/
+
+# 1. Configure the distribution for Docker
+# 2. Ensure directories are created. Most already are, but make sure
+# 3. Apply correct permissions
+# 4. Move the distribution's default logging config aside
+# 5. Generate a docker logging config, to be used by default
+# 6. Apply more correct permissions
+# 7. The JDK's directories' permissions don't allow `java` to be executed under a different
+#    group to the default. Fix this.
+# 8. Ensure that there are no files with setuid or setgid, in order to mitigate "stackclash" attacks.
+# 9. Ensure all files are world-readable by default. It should be possible to
+#    examine the contents of the image under any UID:GID
+RUN sed -i -e 's/ES_DISTRIBUTION_TYPE=tar/ES_DISTRIBUTION_TYPE=docker/' bin/elasticsearch-env && \
+    mkdir -p config/jvm.options.d data logs plugins && \
+    chmod 0775 config config/jvm.options.d data logs plugins && \
+    mv config/log4j2.properties config/log4j2.file.properties && \
+    jdk/bin/java -jar /tmp/transform-log4j-config-7.11.0.jar config/log4j2.file.properties > config/log4j2.properties && \
+    chmod 0660 config/elasticsearch.yml config/log4j2*.properties && \
+    find ./jdk -type d -exec chmod 0755 {} + && \
+    find . -xdev -perm -4000 -exec chmod ug-s {} + && \
+    find . -type f -exec chmod o+r {} +
 
 ################################################################################
 # Build stage 1 (the actual Elasticsearch image):
@@ -56,68 +74,66 @@ RUN chmod 0660 config/elasticsearch.yml config/log4j2.properties
 
 FROM centos:8
 
-ENV ELASTIC_CONTAINER true
-
 RUN for iter in {1..10}; do \
       yum update --setopt=tsflags=nodocs -y && \
       yum install --setopt=tsflags=nodocs -y \
-        nc shadow-utils zip unzip  && \
-      yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" && \
-      sleep 10; \
+      nc shadow-utils zip unzip  && \
+      yum clean all && \
+      exit_code=0 && break || \
+        exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10; \
     done; \
-    (exit $exit_code)
+    exit $exit_code
 
 RUN groupadd -g 1000 elasticsearch && \
     adduser -u 1000 -g 1000 -G 0 -d /usr/share/elasticsearch elasticsearch && \
     chmod 0775 /usr/share/elasticsearch && \
     chown -R 1000:0 /usr/share/elasticsearch
 
+ENV ELASTIC_CONTAINER true
+
 WORKDIR /usr/share/elasticsearch
 COPY --from=builder --chown=1000:0 /usr/share/elasticsearch /usr/share/elasticsearch
-COPY --from=builder --chown=0:0 /tini /tini
-
-# Replace OpenJDK's built-in CA certificate keystore with the one from the OS
-# vendor. The latter is superior in several ways.
-# REF: https://github.com/elastic/elasticsearch-docker/issues/171
-RUN ln -sf /etc/pki/ca-trust/extracted/java/cacerts /usr/share/elasticsearch/jdk/lib/security/cacerts
+COPY --from=builder --chown=0:0 /bin/tini /bin/tini
 
 ENV PATH /usr/share/elasticsearch/bin:$PATH
 
 COPY bin/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
 
-# The JDK's directories' permissions don't allow `java` to be executed under a different
-# group to the default. Fix this.
-RUN find /usr/share/elasticsearch/jdk -type d -exec chmod 0755 '{}' \; && \
-    chmod g=u /etc/passwd && \
-    chmod 0775 /usr/local/bin/docker-entrypoint.sh
-
-# Ensure that there are no files with setuid or setgid, in order to mitigate "stackclash" attacks.
-RUN find / -xdev -perm -4000 -exec chmod ug-s {} +
+# 1. Sync the user and group permissions of /etc/passwd
+# 2. Set correct permissions of the entrypoint
+# 3. Ensure that there are no files with setuid or setgid, in order to mitigate "stackclash" attacks.
+#    We've already run this in previous layers so it ought to be a no-op.
+# 4. Replace OpenJDK's built-in CA certificate keystore with the one from the OS
+#    vendor. The latter is superior in several ways.
+#    REF: https://github.com/elastic/elasticsearch-docker/issues/171
+RUN chmod g=u /etc/passwd && \
+    chmod 0775 /usr/local/bin/docker-entrypoint.sh && \
+    find / -xdev -perm -4000 -exec chmod ug-s {} + && \
+    ln -sf /etc/pki/ca-trust/extracted/java/cacerts /usr/share/elasticsearch/jdk/lib/security/cacerts
 
 EXPOSE 9200 9300
 
-LABEL org.label-schema.build-date="2021-01-13T00:42:12.435326Z" \
-  org.label-schema.license="Elastic-License" \
+LABEL org.label-schema.build-date="2021-02-08T22:44:01.320463Z" \
+  org.label-schema.license="Elastic-License-2.0" \
   org.label-schema.name="Elasticsearch" \
   org.label-schema.schema-version="1.0" \
   org.label-schema.url="https://www.elastic.co/products/elasticsearch" \
   org.label-schema.usage="https://www.elastic.co/guide/en/elasticsearch/reference/index.html" \
-  org.label-schema.vcs-ref="747e1cc71def077253878a59143c1f785afa92b9" \
+  org.label-schema.vcs-ref="8ced7813d6f16d2ef30792e2fcde3e755795ee04" \
   org.label-schema.vcs-url="https://github.com/elastic/elasticsearch" \
   org.label-schema.vendor="Elastic" \
-  org.label-schema.version="7.10.2" \
-  org.opencontainers.image.created="2021-01-13T00:42:12.435326Z" \
+  org.label-schema.version="7.11.0" \
+  org.opencontainers.image.created="2021-02-08T22:44:01.320463Z" \
   org.opencontainers.image.documentation="https://www.elastic.co/guide/en/elasticsearch/reference/index.html" \
-  org.opencontainers.image.licenses="Elastic-License" \
-  org.opencontainers.image.revision="747e1cc71def077253878a59143c1f785afa92b9" \
+  org.opencontainers.image.licenses="Elastic-License-2.0" \
+  org.opencontainers.image.revision="8ced7813d6f16d2ef30792e2fcde3e755795ee04" \
   org.opencontainers.image.source="https://github.com/elastic/elasticsearch" \
   org.opencontainers.image.title="Elasticsearch" \
   org.opencontainers.image.url="https://www.elastic.co/products/elasticsearch" \
   org.opencontainers.image.vendor="Elastic" \
-  org.opencontainers.image.version="7.10.2"
+  org.opencontainers.image.version="7.11.0"
 
-
-ENTRYPOINT ["/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
+ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
 # Dummy overridable parameter parsed by entrypoint
 CMD ["eswrapper"]
 
