Contexts for 8.13.3
This commit was created by the elastic-dockerfiles-publisher.

diff --git a/logstash/Dockerfile b/logstash/Dockerfile
--- a/logstash/Dockerfile
+++ b/logstash/Dockerfile
@@ -1,41 +1,41 @@
-# This Dockerfile was generated from templates/Dockerfile.j2
+# This Dockerfile was generated from templates/Dockerfile.erb
+
+                                    
 FROM ubuntu:20.04
 
 RUN for iter in {1..10}; do \
-export DEBIAN_FRONTEND=noninteractive && \
+  export DEBIAN_FRONTEND=noninteractive && \
 apt-get update -y && \
 apt-get upgrade -y && \
-apt-get install -y procps findutils tar gzip curl && \
-apt-get install -y locales && \
+apt-get install -y procps findutils tar gzip && \
+  apt-get install -y locales && \
+  apt-get install -y curl && \
 apt-get clean all && \
-locale-gen 'en_US.UTF-8' && \
-    apt-get clean metadata && \
+  locale-gen 'en_US.UTF-8' && \
+  apt-get clean metadata && \
 exit_code=0 && break || exit_code=$? && \
-    echo "packaging error: retry $iter in 10s" && \
-    apt-get clean all && \
-apt-get clean metadata && \
+echo "packaging error: retry $iter in 10s" && \
+apt-get clean all && \
+  apt-get clean metadata && \
 sleep 10; done; \
-    (exit $exit_code)
+(exit $exit_code)
 
 # Provide a non-root user to run the process.
 RUN groupadd --gid 1000 logstash && \
-    adduser --uid 1000 --gid 1000 \
-       --home /usr/share/logstash --no-create-home \
-      logstash
+  adduser --uid 1000 --gid 1000 --home /usr/share/logstash --no-create-home logstash
 
 # Add Logstash itself.
-RUN \
-curl -Lo - https://artifacts.elastic.co/downloads/logstash/logstash-7.17.20-linux-$(arch).tar.gz | \
-    tar zxf - -C /usr/share && \
-    mv /usr/share/logstash-7.17.20 /usr/share/logstash && \
-chown --recursive logstash:logstash /usr/share/logstash/ && \
-    chown -R logstash:root /usr/share/logstash && \
-    chmod -R g=u /usr/share/logstash && \
-    mkdir /licenses/ && \
-    mv /usr/share/logstash/NOTICE.TXT /licenses/NOTICE.TXT && \
-    mv /usr/share/logstash/LICENSE.txt /licenses/LICENSE.txt && \
-    find /usr/share/logstash -type d -exec chmod g+s {} \; && \
-    ln -s /usr/share/logstash /opt/logstash
+RUN curl -Lo - https://artifacts.elastic.co/downloads/logstash/logstash-8.13.3-linux-$(arch).tar.gz | \
+  tar zxf - -C /usr/share && \
+  mv /usr/share/logstash-8.13.3 /usr/share/logstash && \
+  chown --recursive logstash:logstash /usr/share/logstash/ && \
+  chown -R logstash:root /usr/share/logstash && \
+  chmod -R g=u /usr/share/logstash && \
+  mkdir /licenses/ && \
+  mv /usr/share/logstash/NOTICE.TXT /licenses/NOTICE.TXT && \
+  mv /usr/share/logstash/LICENSE.txt /licenses/LICENSE.txt && \
+  find /usr/share/logstash -type d -exec chmod g+s {} \; && \
+  ln -s /usr/share/logstash /opt/logstash
 
 WORKDIR /usr/share/logstash
 ENV ELASTIC_CONTAINER true
@@ -43,17 +43,36 @@ ENV PATH=/usr/share/logstash/bin:$PATH
 
 # Provide a minimal configuration, so that simple invocations will provide
 # a good experience.
-ADD config/pipelines.yml config/pipelines.yml
-ADD config/logstash-full.yml config/logstash.yml
-ADD config/log4j2.properties config/
-ADD pipeline/default.conf pipeline/logstash.conf
+COPY config/pipelines.yml config/pipelines.yml
+  COPY config/logstash-full.yml config/logstash.yml
+COPY config/log4j2.properties config/
+COPY config/log4j2.file.properties config/
+COPY pipeline/default.conf pipeline/logstash.conf
+COPY env2yaml/env2yaml-amd64 env2yaml/
+COPY env2yaml/env2yaml-arm64 env2yaml/
+
 RUN chown --recursive logstash:root config/ pipeline/
 # Ensure Logstash gets the correct locale by default.
 ENV LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
-ADD env2yaml/env2yaml /usr/local/bin/
+
+# Copy over the appropriate env2yaml artifact
+RUN env2yamlarch="$(arch)"; \
+  case "${env2yamlarch}" in \
+    'x86_64') \
+      env2yamlarch=amd64; \
+      ;; \
+    'aarch64') \
+      env2yamlarch=arm64; \
+      ;; \
+    *) echo >&2 "error: unsupported architecture '$env2yamlarch'"; exit 1 ;; \
+  esac; \
+  cp env2yaml/env2yaml-${env2yamlarch} /usr/local/bin/env2yaml; \
+  rm -rf env2yaml
 # Place the startup wrapper script.
-ADD bin/docker-entrypoint /usr/local/bin/
+COPY bin/docker-entrypoint /usr/local/bin/
+
 RUN chmod 0755 /usr/local/bin/docker-entrypoint
+
 
 USER 1000
 
@@ -64,13 +83,14 @@ LABEL  org.label-schema.schema-version="1.0" \
   org.opencontainers.image.vendor="Elastic" \
   org.label-schema.name="logstash" \
   org.opencontainers.image.title="logstash" \
-  org.label-schema.version="7.17.20" \
-  org.opencontainers.image.version="7.17.20" \
+  org.label-schema.version="8.13.3" \
+  org.opencontainers.image.version="8.13.3" \
   org.label-schema.url="https://www.elastic.co/products/logstash" \
   org.label-schema.vcs-url="https://github.com/elastic/logstash" \
   org.label-schema.license="Elastic License" \
   org.opencontainers.image.licenses="Elastic License" \
   org.opencontainers.image.description="Logstash is a free and open server-side data processing pipeline that ingests data from a multitude of sources, transforms it, and then sends it to your favorite 'stash.'" \
-  org.label-schema.build-date=2024-03-26T08:47:56+00:00 \
-org.opencontainers.image.created=2024-03-26T08:47:56+00:00
+  org.label-schema.build-date=2024-04-25T21:23:18+00:00 \
+  org.opencontainers.image.created=2024-04-25T21:23:18+00:00
+
 ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
